// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopularDev.Infrastructure.Persistence;

#nullable disable

namespace PopularDev.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203124651_AddUserDetailsTable")]
    partial class AddUserDetailsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PopularDev.Domain.Entities.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .HasColumnType("longtext");

                    b.Property<string>("BitLockerPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientVpnUsername")
                        .HasColumnType("longtext");

                    b.Property<long?>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceHostName")
                        .HasColumnType("longtext");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("HwfhPwfH")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("MachineIpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserLoginId")
                        .HasColumnType("char(36)");

                    b.Property<string>("VdiPhysicalMachineLocation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserLoginId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("PopularDev.Domain.Entities.UsersLogin", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoginId");

                    b.ToTable("UsersLogin");
                });

            modelBuilder.Entity("PopularDev.Domain.Entities.UserDetails", b =>
                {
                    b.HasOne("PopularDev.Domain.Entities.UsersLogin", "UsersLogin")
                        .WithOne()
                        .HasForeignKey("PopularDev.Domain.Entities.UserDetails", "UserLoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
